import { Inter, Playfair_Display } from 'next/font/google'
import './globals.css'
import NextThemeProvider from '../providers/NextThemeProvider'
import Navbar from '@/components/layout/Navbar'

// Body & UI font
const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

// Primary heading font
const playfair = Playfair_Display({
	variable: '--font-playfair',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
			className={`
    ${inter.variable}
    ${playfair.variable}
    h-full antialiased
  `}
		>
			<body className='min-h-full flex flex-col font-(--font-inter)'>
				<NextThemeProvider>
					{/* <Toast.Provider /> */}
					<Navbar />
					<main className='min-h-screen'>{children}</main>
					{/* <Footer /> */}
				</NextThemeProvider>
			</body>
		</html>
	)
}
