import { Inter, Playfair_Display } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import NextThemeProvider from '../../providers/NextThemeProvider'
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import { ToastContainer } from 'react-toastify'

// Body & UI font
const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

// Primary heading font
const playfair = Playfair_Display({
	variable: '--font-playfair',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
			className={`${inter.variable} ${playfair.variable} h-screen antialiased`}
		>
			<body className='min-h-full flex flex-col font-(--font-inter)'>
				<NextThemeProvider>
					<ToastContainer
						position='top-right'
						autoClose={4000}
						hideProgressBar={false}
						newestOnTop={true}
						closeOnClick
						pauseOnHover
						draggable
						theme='light'
					/>
					<Navbar />
					<main className='min-h-screen'>{children}</main>
					<Footer />
				</NextThemeProvider>
			</body>
		</html>
	)
}
